// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcOG2GY7MJWSIGWN-ZUFp8jwJ1VJ0PcU',
    appId: '1:371047090151:web:d391989a69dfe529119f42',
    messagingSenderId: '371047090151',
    projectId: 'riverpod-firestore-strea-6926b',
    authDomain: 'riverpod-firestore-strea-6926b.firebaseapp.com',
    storageBucket: 'riverpod-firestore-strea-6926b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgad3DFQ4VXoxl90busqMV9-7QbWeTAbk',
    appId: '1:371047090151:android:7379c07e6330d60e119f42',
    messagingSenderId: '371047090151',
    projectId: 'riverpod-firestore-strea-6926b',
    storageBucket: 'riverpod-firestore-strea-6926b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfdSH37CLxhMygcMXUveihrUuR3zOmyCc',
    appId: '1:371047090151:ios:368e0f17a2162a4e119f42',
    messagingSenderId: '371047090151',
    projectId: 'riverpod-firestore-strea-6926b',
    storageBucket: 'riverpod-firestore-strea-6926b.appspot.com',
    iosClientId: '371047090151-0ni6apapjlo3aef82jirgvjunduhem04.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreSteam1',
  );
}
